name: Buld & Publish (Firefox)

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        run: npm run build:ff

      - name: Fix firefox manifest
        run: sed -i 's/background\/scripts\.js/background\/service_worker\.js/g' dist/firefox/manifest.json

      - name: Put the extension into a zip file
        run: zip -r release_firefox.zip dist/firefox

      - name: Upload to Mozilla Addons
        uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: "ghcss-extension@bims.sh"
          addon-path: "release_firefox.zip"
          auth-api-issuer: ${{ secrets.FIREFOX_KEY }}
          auth-api-secret: ${{ secrets.FIREFOX_SECRET }}
