name: Buld & Publish (Firefox)

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Create a source-code zip file
        run: zip -r source-code.zip ./**

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        run: npm run build:ff

      - name: Fix firefox manifest
        run: sed -i 's/background\/scripts\.js/background\/service_worker\.js/g' dist/firefox/manifest.json

      - name: Put the extension into a zip file
        run: zip -r release_firefox.zip dist/firefox

      - name: Upload to Mozilla Addons
        uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: "ghcss-extension@bims.sh"
          addon-path: "release_firefox.zip"
          source-path: "source-code.zip"
          approval-note: |
            The instructions are inside the README.md under the "Build" section.
            Also make sure to check the note right below them.
          auth-api-issuer: ${{ secrets.FIREFOX_KEY }}
          auth-api-secret: ${{ secrets.FIREFOX_SECRET }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release_firefox.zip
          asset_name: release_firefox.zip
          asset_content_type: application/zip